#!perl

use 5.010001;
use strict;
use warnings;

die "Not yet implemented!";

# ABSTRACT: (NOT YET IMPLEMENTED) Convert spreadsheet from one format (e.g. LibreOffice Calc) to another (e.g. XLSX)

=head1 SYNOPSIS

 % ss2ss foo.xlsx foo.ods


=head1 DESCRIPTION


=head1 SEE ALSO
